# Generated by Django 5.0.7 on 2024-07-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviecollection", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="uuid",
            new_name="movie_id",
        ),
    ]
