# Generated by Django 5.0.7 on 2024-07-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviecollection", "0003_rename_uuid_movie_movie_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
