# Generated by Django 5.0.7 on 2024-07-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviecollection", "0004_alter_collection_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movie_id",
            field=models.UUIDField(),
        ),
    ]
