# Generated by Django 5.0.7 on 2024-07-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviecollection", "0005_alter_movie_movie_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
