# Generated by Django 5.0.7 on 2024-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviecollection", "0007_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
