# Generated by Django 5.0.7 on 2024-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviecollection", "0008_alter_collection_title"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_user_title"
            ),
        ),
    ]
